### ISSUE TITLE
Welcome 페이지 레이아웃 구현

### ISSUE THREAD

**Issue by harry7435** [1e5i-Shark/algobaro-fe#69]
## 📝 설명

Welcome(시작) 페이지 레이아웃을 구현합니다.

## ✅ 이슈 유형

- [x] CSS 등 사용자 UI 디자인 변경

## 💻 작업 내용

- [x] Welcome 페이지 레이아웃 구현
  - [x] 인증 시 홈 버튼 보이기
  - [x] 미 인증 시 로그인 폼 보이기
  - [x] 알고바로 기본 설명 영역 구현

**Comment by SoJuSo** [comment]
웰컴~.~
