### ISSUE TITLE
공통 컴포넌트 Modal 구현

### ISSUE THREAD

**Issue by harry7435** [1e5i-Shark/algobaro-fe#8]
## 📝 설명
Modal 공용 컴포넌트를 구현합니다.

## ✅ 이슈 유형

- [x] 새로운 기능 추가
- [x] CSS 등 사용자 UI 디자인 변경

## 💻 작업 내용

- [x] Modal 컴포넌트 구현 방식 결정
- [x] 레이아웃 설계
- [x] 크기 및 이벤트 관련 props 추가
- [x] Modal 관련 추가 리팩토링(https://github.com/1e5i-Shark/algobaro-fe/issues/8#issuecomment-1979997970)
  - [x] mode props 추가
    - normal: X 버튼 존재, overlay 클릭 시 onClose
    - confirm: X 버튼 없음, overlay 클릭 시 onClose 되지 않게
  - [x] z-index 적용
    - theme.ZINDEX.MODAL
  - [x] 모바일 vh 이슈 해결
    - ModalWrapper의 너비, 높이를 100%로 설정
  - [x] 스크롤 막아주기

#### 추가 컴포넌트 수정 요청 사항
- [x] Input.tsx : 83번째 줄 isDirty 조건 삭제

**Comment by pySoo** [comment]
작업 부탁드립니다 모달 총책임자님 👍

## 모달 업그레이드 내용

- mode props 추가
  - `normal`: X 버튼 존재, overlay 클릭 시 onClose
  - `confirm`: X 버튼 없음, overlay 클릭 시 onClose 되지 않게

- z-index 적용
  - theme.ZINDEX.MODAL

**Comment by harry7435** [comment]
### 추가 컴포넌트 수정 요청 사항
- `Input.tsx` : 83번째 줄 isDirty 조건 삭제
